version: '3.8'

services:

  postgres:
    image: postgres:16

    container_name: ecommerce-db

    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <password here>

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: ecommerce-api

    ports:
      - "8080:8080"
    
    volumes:
      - ./wwwroot:/app/wwwroot

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: <insert POSTGRES_PASSWORD here>

volumes:
  postgres_data:
