spring.application.name=sandboxproj
spring.datasource.url= <db connection url here>
spring.datasource.username= <db username>
spring.datasource.password=<db password>


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format.sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

jwt.secret=<JWT signing key here>
jwt.expiration=<JWT token expiration time here>

server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=50MB
